// Dati d'impatto: tutte le cifre provengono dalle fonti citate (report ufficiali
// dei produttori, studi accademici, inchieste). Aggiornato: luglio 2026.

const FONTI = {
  socInjuries: {
    label: "Strategic Organizing Center — Failure to Deliver (2025)",
    url: "https://thesoc.org/resources/failure-to-deliver-amazon-falls-short-on-safety/",
  },
  senateAmazon: {
    label: "Commissione HELP Senato USA — The Injury-Productivity Trade-off",
    url: "https://www.help.senate.gov/imo/media/doc/amazon_investigation.pdf",
  },
  amnestyCobalt: {
    label: "Amnesty International — This Is What We Die For (cobalto, RDC)",
    url: "https://www.amnesty.org/en/documents/afr62/3183/2016/en/",
  },
  guardianFoxconn: {
    label: "The Guardian — Life and death in Apple's forbidden city (Foxconn)",
    url: "https://www.theguardian.com/technology/2017/jun/18/foxconn-life-death-forbidden-city-longhua-suicide-apple-iphone-brian-merchant-one-device-extract",
  },
  watchRuling: {
    label: "Tribunale di Francoforte vieta la pubblicità \"CO₂ neutrale\" dell'Apple Watch",
    url: "https://www.notebookcheck.net/Apple-Watch-Series-10-is-not-climate-neutral-Court-prohibits-greenwashing-marketing.1097378.0.html",
  },
  cambridgePs4: {
    label: "University of Cambridge IfM — impatto ambientale della PlayStation 4",
    url: "https://www.ifm.eng.cam.ac.uk/insights/sustainability/the-environmental-impact-of-a-playstation-4/",
  },
  mongabayConsole: {
    label: "Mongabay — l'impatto ambientale delle console (2022)",
    url: "https://news.mongabay.com/2022/10/playing-dangerously-the-environmental-impact-of-video-gaming-consoles/",
  },
  samsungEpd: {
    label: "Samsung — Product Environmental Report QLED 55\" (EPD)",
    url: "https://www.samsung.com/global/sustainability/media/pdf/TV_QLED_Environmental_Report_EN.pdf",
  },
  bbcSamsungWorkers: {
    label: "BBC — le scuse di Samsung ai lavoratori ammalati nelle fabbriche di chip",
    url: "https://www.bbc.com/news/business-46349435",
  },
  vacuumLca: {
    label: "Gallego-Schmid et al., Science of the Total Environment (2016) — LCA aspirapolveri",
    url: "https://www.sciencedirect.com/science/article/pii/S0048969716305745",
  },
  legoFortune: {
    label: "Fortune — LEGO, plastica riciclata ed emissioni (2023)",
    url: "https://fortune.com/europe/2023/09/25/lego-scraps-plans-bricks-plastic-bottles-rpet-higher-carbon-emissions/",
  },
  waterSmartphone: {
    label: "Waterwise — Virtual water footprint (~12.760 L per smartphone)",
    url: "https://waterwise.org.uk/virtual-water-footprint/",
  },
  hiddenWater: {
    label: "Water Footprint Calculator — The hidden water in everyday products",
    url: "https://watercalculator.org/footprint/the-hidden-water-in-everyday-products/",
  },
  knowTheChain: {
    label: "KnowTheChain — benchmark diritti dei lavoratori nella filiera ICT",
    url: "https://knowthechain.org/",
  },
  ewasteMonitor: {
    label: "Global E-waste Monitor 2024 (ONU): 62 Mt di rifiuti elettronici, <25% riciclato",
    url: "https://ewastemonitor.info/",
  },
  chinaLaborWatch: {
    label: "China Labor Watch — inchieste sulle fabbriche di elettronica in Cina",
    url: "https://chinalaborwatch.org/",
  },
};

// Flag "lavoro" riusabili
const LAVORO = {
  magazziniAmazon: {
    text: "Nei magazzini Amazon USA il tasso di infortuni è 6,5 ogni 100 addetti — più del doppio di Walmart. Nel 2024 Amazon impiegava il 39% dei magazzinieri USA ma causava il 56% degli infortuni gravi del settore.",
    fonte: FONTI.socInjuries,
  },
  ritmiAmazon: {
    text: "Un'indagine del Senato USA (2024) documenta che Amazon conosce il legame tra ritmi imposti e infortuni, e ha scelto di non rallentare le linee.",
    fonte: FONTI.senateAmazon,
  },
  assemblaggiaCina: {
    text: "Assemblato in fabbriche cinesi dove inchieste indipendenti documentano straordinari oltre i limiti di legge e salari base insufficienti.",
    fonte: FONTI.chinaLaborWatch,
  },
  foxconn: {
    text: "Assemblato principalmente da Foxconn, dove sono documentati turni estenuanti; la crisi dei suicidi del 2010 portò all'installazione di reti anti-suicidio nei dormitori.",
    fonte: FONTI.guardianFoxconn,
  },
  cobalto: {
    text: "Il cobalto delle batterie proviene in gran parte dalla Rep. Dem. del Congo, dove Amnesty ha documentato lavoro minorile nelle miniere artigianali. (Apple dichiara oggi cobalto 100% riciclato nelle batterie dei modelli recenti.)",
    fonte: FONTI.amnestyCobalt,
  },
  cobaltoGenerico: {
    text: "Le batterie al litio contengono cobalto: Amnesty ha documentato lavoro minorile nelle miniere artigianali della Rep. Dem. del Congo.",
    fonte: FONTI.amnestyCobalt,
  },
  samsungFab: {
    text: "Samsung si è scusata pubblicamente (2018) con i lavoratori delle sue fabbriche di semiconduttori ammalatisi di leucemia e altre patologie, dopo oltre dieci anni di vertenze.",
    fonte: FONTI.bbcSamsungWorkers,
  },
  trasparenzaNintendo: {
    text: "Nintendo non pubblica un'analisi del ciclo di vita dei suoi prodotti e ottiene punteggi bassi nei benchmark sulla trasparenza della filiera (KnowTheChain).",
    fonte: FONTI.knowTheChain,
  },
  legoOk: {
    text: "Onestà impone di dirlo: le condizioni di lavoro nelle fabbriche LEGO risultano tra le migliori del settore giocattoli. Il problema qui è la materia prima, non chi la lavora.",
    fonte: FONTI.legoFortune,
  },
};

// transparency: "ufficiale" = dato del produttore certificato/verificato
//               "stima"     = studio indipendente o proxy dichiarato
//               "assente"   = il produttore non pubblica nulla
const PRODOTTI = [
  {
    id: "echo-dot-max",
    emoji: "🔊",
    tile: "#232f3e",
    nome: "Amazon Echo Dot Max",
    marca: "Amazon",
    prezzo: 99.99,
    stelle: 4.7, recensioni: "214.380",
    co2: 89,
    co2Nota: "Ciclo di vita completo, dato Amazon certificato Carbon Trust.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Echo Dot Max", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_echo_dot_max.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: "La produzione dei chip richiede acqua ultrapura in regioni spesso già in stress idrico.",
    lavoro: [LAVORO.magazziniAmazon, LAVORO.ritmiAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "fire-tv-stick-4k",
    emoji: "📺",
    tile: "#232f3e",
    nome: "Fire TV Stick 4K (2ª gen)",
    marca: "Amazon",
    prezzo: 69.99,
    stelle: 4.7, recensioni: "512.443",
    co2: 33,
    co2Nota: "Ciclo di vita completo, dato Amazon certificato Carbon Trust.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Fire TV Stick 4K", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_fire_tv_stick_4k.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "kindle-paperwhite",
    emoji: "📖",
    tile: "#232f3e",
    nome: "Kindle Paperwhite 16 GB (12ª gen)",
    marca: "Amazon",
    prezzo: 169.99,
    stelle: 4.6, recensioni: "88.120",
    co2: 35,
    co2Nota: "Ciclo di vita completo, dato Amazon certificato SCS Global Services. Pareggia l'impronta di ~30 libri cartacei: conviene solo se lo usi per anni.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Kindle Paperwhite", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_kindle_paperwhite_16gb.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "ring-battery-doorbell",
    emoji: "🚪",
    tile: "#1d3557",
    nome: "Ring Battery Doorbell",
    marca: "Amazon / Ring",
    prezzo: 99.99,
    stelle: 4.5, recensioni: "163.207",
    co2: 19,
    co2Nota: "Ciclo di vita completo, dato Amazon.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Ring Battery Doorbell", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_ring_battery_doorbell.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "blink-mini-2",
    emoji: "📷",
    tile: "#1d3557",
    nome: "Blink Mini 2",
    marca: "Amazon / Blink",
    prezzo: 39.99,
    stelle: 4.4, recensioni: "301.552",
    co2: 24,
    co2Nota: "Ciclo di vita completo, dato Amazon.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Blink Mini 2", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_blink_mini_2.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "iphone-17",
    emoji: "📱",
    tile: "#1c1c1e",
    nome: "Apple iPhone 17 (256 GB)",
    marca: "Apple",
    prezzo: 979,
    stelle: 4.8, recensioni: "45.960",
    co2: 55,
    co2Nota: "Ciclo di vita completo, Product Environmental Report Apple (ISO 14067). L'80% circa nasce in produzione, prima ancora che il telefono si accenda.",
    co2Fonte: { label: "Apple — iPhone 17 Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/iphone/iPhone_17_PER_Sept2025.pdf" },
    transparency: "ufficiale",
    acquaL: 12760,
    acquaNota: "Acqua \"nascosta\" media per produrre uno smartphone: estrazione dei metalli e fabbricazione dei chip.",
    acquaFonte: FONTI.waterSmartphone,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "airpods-pro-3",
    emoji: "🎧",
    tile: "#f5f5f7",
    emojiDark: true,
    nome: "Apple AirPods Pro 3",
    marca: "Apple",
    prezzo: 249,
    stelle: 4.7, recensioni: "112.033",
    co2: 13,
    co2Nota: "Ciclo di vita completo, PER Apple. Le batterie incollate non sono sostituibili: a fine vita (~4-5 anni) diventano rifiuto elettronico quasi non riciclabile.",
    co2Fonte: { label: "Apple — AirPods Pro 3 Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/airpods/Apple_AirPods_Pro_3_PER_Sept2025.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "apple-watch-s10",
    emoji: "⌚",
    tile: "#1c1c1e",
    nome: "Apple Watch Series 10",
    marca: "Apple",
    prezzo: 449,
    stelle: 4.8, recensioni: "67.421",
    co2: 8.4,
    co2Nota: "Dato Apple (già al netto delle riduzioni dichiarate). Apple lo vendeva come \"CO₂ neutrale\" grazie a crediti di compensazione: un tribunale tedesco ha vietato questa pubblicità come ingannevole.",
    co2Fonte: { label: "Apple — Apple Watch Series 10 Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/watch/Apple_Watch_Series_10_PER_Sept2024.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto, { text: "Il marketing \"carbon neutral\" di questo prodotto è stato dichiarato ingannevole da un tribunale di Francoforte.", fonte: FONTI.watchRuling }],
  },
  {
    id: "macbook-air-m5",
    emoji: "💻",
    tile: "#1c1c1e",
    nome: "Apple MacBook Air 13\" (M5)",
    marca: "Apple",
    prezzo: 1249,
    stelle: 4.8, recensioni: "23.874",
    co2: 119,
    co2Nota: "Configurazione base, ciclo di vita completo, PER Apple (fino a 165 kg per le configurazioni maggiori).",
    co2Fonte: { label: "Apple — MacBook Air (M5) Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/notebooks/MacBook_Air_M5_PER_Mar2026.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: "I chip avanzati richiedono enormi volumi di acqua ultrapura nelle fonderie di Taiwan, area a ricorrente crisi idrica.",
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "ipad-10",
    emoji: "📲",
    tile: "#1c1c1e",
    nome: "Apple iPad (10ª gen, 64 GB)",
    marca: "Apple",
    prezzo: 439,
    stelle: 4.8, recensioni: "94.115",
    co2: 72,
    co2Nota: "Ciclo di vita completo, PER Apple.",
    co2Fonte: { label: "Apple — iPad (10th generation) Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/ipad/iPad_PER_Oct2022.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "ps5",
    emoji: "🎮",
    tile: "#00439c",
    nome: "Sony PlayStation 5",
    marca: "Sony",
    prezzo: 549,
    stelle: 4.8, recensioni: "78.930",
    co2: 89,
    co2Nota: "Sony non pubblica l'LCA completa della PS5: 89 kg è il dato di produzione+trasporto della PS4 (Univ. di Cambridge), usato come proxy prudente. L'uso aggiunge ~0,022 kg CO₂ l'ora: con 2 ore al giorno per 5 anni sono altri ~80 kg.",
    co2Fonte: FONTI.cambridgePs4,
    transparency: "stima",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "switch-2",
    emoji: "🕹️",
    tile: "#e60012",
    nome: "Nintendo Switch 2",
    marca: "Nintendo",
    prezzo: 469,
    stelle: 4.8, recensioni: "51.204",
    co2: null,
    co2Nota: "Nintendo non pubblica alcuna analisi del ciclo di vita. Gli studi indipendenti stimano per la Switch originale ~13,8 kg CO₂ l'anno di solo uso. Il dato di produzione resta un segreto aziendale.",
    co2Fonte: FONTI.mongabayConsole,
    transparency: "assente",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.trasparenzaNintendo, LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "samsung-qled-55",
    emoji: "🖥️",
    tile: "#111111",
    nome: "Samsung QLED 55\" 4K",
    marca: "Samsung",
    prezzo: 649,
    stelle: 4.6, recensioni: "37.617",
    co2: 1123,
    co2Nota: "EPD ufficiale Samsung (QLED 55\", vita 5 anni): 1.122,7 kg CO₂e totali, di cui ~725 kg dal solo uso e ~375 kg da materiali e produzione. L'articolo più pesante di questo negozio.",
    co2Fonte: FONTI.samsungEpd,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.samsungFab, LAVORO.assemblaggiaCina],
  },
  {
    id: "robot-aspirapolvere",
    emoji: "🤖",
    tile: "#3a3a3a",
    nome: "Robot aspirapolvere Wi-Fi",
    marca: "iRobot / Ecovacs (tipo)",
    prezzo: 299,
    stelle: 4.4, recensioni: "142.883",
    co2: 312,
    co2Nota: "I produttori di robot aspirapolvere non pubblicano LCA: 312 kg è il ciclo di vita di un aspirapolvere di riferimento in uno studio peer-reviewed (~80% dall'uso). Batteria e sensori del robot tendono ad alzare la parte di produzione.",
    co2Fonte: FONTI.vacuumLca,
    transparency: "stima",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "lego-1000",
    emoji: "🧱",
    tile: "#ffcf00",
    emojiDark: true,
    nome: "Set LEGO da ~1.000 pezzi",
    marca: "LEGO",
    prezzo: 159.99,
    stelle: 4.9, recensioni: "28.442",
    co2: 40,
    co2Nota: "Stima 20-60 kg CO₂e per 1.000 mattoncini in ABS (qui usiamo il valore centrale, 40 kg). Servono ~2 kg di petrolio per ogni kg di ABS; il piano LEGO per mattoncini in PET riciclato è stato abbandonato perché avrebbe aumentato le emissioni.",
    co2Fonte: FONTI.legoFortune,
    transparency: "stima",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.legoOk],
  },
];

// Fattori per le equivalenze dello scontrino (valori medi, indicativi)
const EQUIV = {
  kgCo2PerKmAuto: 0.17,   // auto media europea, uso reale
  kgCo2PerAlberoAnno: 25, // assorbimento medio annuo di un albero
  litriPerDoccia: 65,     // doccia media
};
