// Dati d'impatto: tutte le cifre provengono dalle fonti citate (report ufficiali
// dei produttori, studi accademici, inchieste). Aggiornato: luglio 2026.

const FONTI = {
  socInjuries: {
    label: "Strategic Organizing Center — Failure to Deliver (2025)",
    url: "https://thesoc.org/resources/failure-to-deliver-amazon-falls-short-on-safety/",
  },
  senateAmazon: {
    label: "Commissione HELP Senato USA — The Injury-Productivity Trade-off",
    url: "https://www.help.senate.gov/imo/media/doc/amazon_investigation.pdf",
  },
  amnestyCobalt: {
    label: "Amnesty International — This Is What We Die For (cobalto, RDC)",
    url: "https://www.amnesty.org/en/documents/afr62/3183/2016/en/",
  },
  guardianFoxconn: {
    label: "The Guardian — Life and death in Apple's forbidden city (Foxconn)",
    url: "https://www.theguardian.com/technology/2017/jun/18/foxconn-life-death-forbidden-city-longhua-suicide-apple-iphone-brian-merchant-one-device-extract",
  },
  watchRuling: {
    label: "Tribunale di Francoforte vieta la pubblicità \"CO₂ neutrale\" dell'Apple Watch",
    url: "https://www.notebookcheck.net/Apple-Watch-Series-10-is-not-climate-neutral-Court-prohibits-greenwashing-marketing.1097378.0.html",
  },
  cambridgePs4: {
    label: "University of Cambridge IfM — impatto ambientale della PlayStation 4",
    url: "https://www.ifm.eng.cam.ac.uk/insights/sustainability/the-environmental-impact-of-a-playstation-4/",
  },
  mongabayConsole: {
    label: "Mongabay — l'impatto ambientale delle console (2022)",
    url: "https://news.mongabay.com/2022/10/playing-dangerously-the-environmental-impact-of-video-gaming-consoles/",
  },
  samsungEpd: {
    label: "Samsung — Product Environmental Report QLED 55\" (EPD)",
    url: "https://www.samsung.com/global/sustainability/media/pdf/TV_QLED_Environmental_Report_EN.pdf",
  },
  bbcSamsungWorkers: {
    label: "BBC — le scuse di Samsung ai lavoratori ammalati nelle fabbriche di chip",
    url: "https://www.bbc.com/news/business-46349435",
  },
  vacuumLca: {
    label: "Gallego-Schmid et al., Science of the Total Environment (2016) — LCA aspirapolveri",
    url: "https://www.sciencedirect.com/science/article/pii/S0048969716305745",
  },
  legoFortune: {
    label: "Fortune — LEGO, plastica riciclata ed emissioni (2023)",
    url: "https://fortune.com/europe/2023/09/25/lego-scraps-plans-bricks-plastic-bottles-rpet-higher-carbon-emissions/",
  },
  waterSmartphone: {
    label: "Waterwise — Virtual water footprint (~12.760 L per smartphone)",
    url: "https://waterwise.org.uk/virtual-water-footprint/",
  },
  hiddenWater: {
    label: "Water Footprint Calculator — The hidden water in everyday products",
    url: "https://watercalculator.org/footprint/the-hidden-water-in-everyday-products/",
  },
  knowTheChain: {
    label: "KnowTheChain — benchmark diritti dei lavoratori nella filiera ICT",
    url: "https://knowthechain.org/",
  },
  ewasteMonitor: {
    label: "Global E-waste Monitor 2024 (ONU): 62 Mt di rifiuti elettronici, <25% riciclato",
    url: "https://ewastemonitor.info/",
  },
  chinaLaborWatch: {
    label: "China Labor Watch — inchieste sulle fabbriche di elettronica in Cina",
    url: "https://chinalaborwatch.org/",
  },
  fairphoneLca: {
    label: "Fairphone — Life Cycle Assessment of the Fairphone 5 (2024)",
    url: "https://www.fairphone.com/wp-content/uploads/2024/09/Fairphone5_LCA_Report_2024.pdf",
  },
  fairphoneFair: {
    label: "Fairphone — materiali equi e azione sul clima (oro Fairtrade, cobalto equo, salario di sussistenza)",
    url: "https://www.fairphone.com/en/impact/climate-action/",
  },
  fraunhoferFairphone: {
    label: "Fraunhofer IZM — tenere il telefono 5 anni taglia l'impatto annuo di circa il 31%",
    url: "https://www.izm.fraunhofer.de/en/news_events/tech_news/keeping-phones-for-5-years-cuts-yearly-impact-on-global-warming.html",
  },
  googlePixelPer: {
    label: "Google — Pixel 9 Product Environmental Report",
    url: "https://sustainability.google/reports/pixel-9-product-environmental-report/",
  },
  samsungS24Per: {
    label: "Samsung — Galaxy S24 Ultra Product Environmental Report (verifica Carbon Trust, PAS 2050)",
    url: "https://www.samsung.com/global/sustainability/media/pdf/Galaxy_S24_Ultra_Environmental_Report_EN.pdf",
  },
  appleMbpM4: {
    label: "Apple — MacBook Pro 14\" (M4) Product Environmental Report (ottobre 2024)",
    url: "https://www.apple.com/environment/pdf/products/notebooks/MacBook_Pro_14-inch_PER_Oct2024.pdf",
  },
  appleMacMiniM4: {
    label: "Apple — Mac mini (M4) Product Environmental Report (ottobre 2024)",
    url: "https://www.apple.com/environment/pdf/products/desktops/Mac_mini_PER_Oct2024.pdf",
  },
  appleTvPer: {
    label: "Apple — Apple TV 4K (3ª gen) Product Environmental Report (ottobre 2022)",
    url: "https://www.apple.com/environment/pdf/products/appletv/Apple_TV_4K_PER_Oct2022.pdf",
  },
  microsoftSurface: {
    label: "Microsoft — Surface Laptop 13\" Eco Profile",
    url: "https://www.microsoft.com/content/dam/microsoft/mlsd/documents/presentations/en-us/surface/MSFT-echo-Ecoprofile-SurfaceLaptop-13inch.pdf",
  },
  dellXps: {
    label: "Dell — Product Carbon Footprint XPS 13 (9350), datasheet 2024 (PAIA, ISO 14040)",
    url: "https://www.delltechnologies.com/asset/en-us/products/laptops-and-2-in-1s/technical-support/xps-13-9350-pcf-datasheet.pdf",
  },
  amazonEchoShow8: {
    label: "Amazon — Product Sustainability Fact Sheet Echo Show 8 (3ª gen)",
    url: "https://sustainability.aboutamazon.com/devices_fact_sheet_echo_show_8.pdf",
  },
  amazonEchoPop: {
    label: "Amazon — Product Sustainability Fact Sheet Echo Pop",
    url: "https://sustainability.aboutamazon.com/devices_fact_sheet_echo_pop.pdf",
  },
  logitechPcf: {
    label: "Logitech — Carbon Impact Labeling & LCA Methodology (ISO 14067, revisione DEKRA)",
    url: "https://www.logitech.com/en-us/sustainability/carbon-impact-methodology",
  },
};

// Flag "lavoro" riusabili
const LAVORO = {
  magazziniAmazon: {
    text: "Nei magazzini Amazon USA il tasso di infortuni è 6,5 ogni 100 addetti — più del doppio di Walmart. Nel 2024 Amazon impiegava il 39% dei magazzinieri USA ma causava il 56% degli infortuni gravi del settore.",
    fonte: FONTI.socInjuries,
  },
  ritmiAmazon: {
    text: "Un'indagine del Senato USA (2024) documenta che Amazon conosce il legame tra ritmi imposti e infortuni, e ha scelto di non rallentare le linee.",
    fonte: FONTI.senateAmazon,
  },
  assemblaggiaCina: {
    text: "Assemblato in fabbriche cinesi dove inchieste indipendenti documentano straordinari oltre i limiti di legge e salari base insufficienti.",
    fonte: FONTI.chinaLaborWatch,
  },
  foxconn: {
    text: "Assemblato principalmente da Foxconn, dove sono documentati turni estenuanti; la crisi dei suicidi del 2010 portò all'installazione di reti anti-suicidio nei dormitori.",
    fonte: FONTI.guardianFoxconn,
  },
  cobalto: {
    text: "Il cobalto delle batterie proviene in gran parte dalla Rep. Dem. del Congo, dove Amnesty ha documentato lavoro minorile nelle miniere artigianali. (Apple dichiara oggi cobalto 100% riciclato nelle batterie dei modelli recenti.)",
    fonte: FONTI.amnestyCobalt,
  },
  cobaltoGenerico: {
    text: "Le batterie al litio contengono cobalto: Amnesty ha documentato lavoro minorile nelle miniere artigianali della Rep. Dem. del Congo.",
    fonte: FONTI.amnestyCobalt,
  },
  samsungFab: {
    text: "Samsung si è scusata pubblicamente (2018) con i lavoratori delle sue fabbriche di semiconduttori ammalatisi di leucemia e altre patologie, dopo oltre dieci anni di vertenze.",
    fonte: FONTI.bbcSamsungWorkers,
  },
  trasparenzaNintendo: {
    text: "Nintendo non pubblica un'analisi del ciclo di vita dei suoi prodotti e ottiene punteggi bassi nei benchmark sulla trasparenza della filiera (KnowTheChain).",
    fonte: FONTI.knowTheChain,
  },
  legoOk: {
    text: "Onestà impone di dirlo: le condizioni di lavoro nelle fabbriche LEGO risultano tra le migliori del settore giocattoli. Il problema qui è la materia prima, non chi la lavora.",
    fonte: FONTI.legoFortune,
  },
  fairphoneEtico: {
    text: "L'eccezione del negozio: Fairphone paga un bonus di salario di sussistenza agli operai di assemblaggio, usa oro certificato Fairtrade e cobalto da filiere sotto audit, e progetta il telefono per essere riparato (10 moduli sostituibili, 10/10 su iFixit). Non risolve tutto, ma è l'opposto dell'usa-e-getta.",
    fonte: FONTI.fairphoneFair,
  },
  logitechEtichetta: {
    text: "Logitech è stata la prima azienda di elettronica di consumo a stampare un'\"etichetta di carbonio\" su ogni prodotto (revisione ISO 14067 di DEKRA). Trasparenza rara nel settore; l'assemblaggio resta però in Cina.",
    fonte: FONTI.logitechPcf,
  },
};

// transparency: "ufficiale" = dato del produttore certificato/verificato
//               "stima"     = studio indipendente o proxy dichiarato
//               "assente"   = il produttore non pubblica nulla
const PRODOTTI = [
  {
    id: "echo-show-8",
    emoji: "🔊",
    tile: "#232f3e",
    nome: "Amazon Echo Show 8 (3ª gen)",
    marca: "Amazon",
    prezzo: 169.99,
    stelle: 4.7, recensioni: "214.380",
    co2: 135,
    co2Nota: "Ciclo di vita completo (fact sheet Amazon, revisione Carbon Trust con reasonable assurance): 135 kg CO₂e, di cui il 64% dal solo uso — un display sempre acceso pesa. Materiali e produzione il 33%.",
    co2Fonte: FONTI.amazonEchoShow8,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: "La produzione dei chip richiede acqua ultrapura in regioni spesso già in stress idrico.",
    lavoro: [LAVORO.magazziniAmazon, LAVORO.ritmiAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "echo-pop",
    emoji: "🎙️",
    tile: "#232f3e",
    nome: "Amazon Echo Pop",
    marca: "Amazon",
    prezzo: 54.99,
    stelle: 4.6, recensioni: "189.402",
    co2: 42,
    co2Nota: "Ciclo di vita completo (fact sheet Amazon, revisione Carbon Trust): 42 kg CO₂e, di cui 24 kg (57%) dal solo uso. Contiene il 3% di materiali riciclati.",
    co2Fonte: FONTI.amazonEchoPop,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.ritmiAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "fire-tv-stick-4k",
    emoji: "📺",
    tile: "#232f3e",
    nome: "Fire TV Stick 4K (2ª gen)",
    marca: "Amazon",
    prezzo: 69.99,
    stelle: 4.7, recensioni: "512.443",
    co2: 33,
    co2Nota: "Ciclo di vita completo, dato Amazon certificato Carbon Trust.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Fire TV Stick 4K", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_fire_tv_stick_4k.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "kindle-paperwhite",
    emoji: "📖",
    tile: "#232f3e",
    nome: "Kindle Paperwhite 16 GB (12ª gen)",
    marca: "Amazon",
    prezzo: 169.99,
    stelle: 4.6, recensioni: "88.120",
    co2: 35,
    co2Nota: "Ciclo di vita completo, dato Amazon certificato SCS Global Services. Pareggia l'impronta di ~30 libri cartacei: conviene solo se lo usi per anni.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Kindle Paperwhite", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_kindle_paperwhite_16gb.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "ring-battery-doorbell",
    emoji: "🚪",
    tile: "#1d3557",
    nome: "Ring Battery Doorbell",
    marca: "Amazon / Ring",
    prezzo: 99.99,
    stelle: 4.5, recensioni: "163.207",
    co2: 19,
    co2Nota: "Ciclo di vita completo, dato Amazon.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Ring Battery Doorbell", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_ring_battery_doorbell.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "blink-mini-2",
    emoji: "📷",
    tile: "#1d3557",
    nome: "Blink Mini 2",
    marca: "Amazon / Blink",
    prezzo: 39.99,
    stelle: 4.4, recensioni: "301.552",
    co2: 24,
    co2Nota: "Ciclo di vita completo, dato Amazon.",
    co2Fonte: { label: "Amazon — Product Sustainability Fact Sheet Blink Mini 2", url: "https://sustainability.aboutamazon.com/devices_fact_sheet_blink_mini_2.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.magazziniAmazon, LAVORO.assemblaggiaCina],
  },
  {
    id: "iphone-17",
    emoji: "📱",
    tile: "#1c1c1e",
    nome: "Apple iPhone 17 (256 GB)",
    marca: "Apple",
    prezzo: 979,
    stelle: 4.8, recensioni: "45.960",
    co2: 55,
    co2Nota: "Ciclo di vita completo, Product Environmental Report Apple (ISO 14067). L'80% circa nasce in produzione, prima ancora che il telefono si accenda.",
    co2Fonte: { label: "Apple — iPhone 17 Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/iphone/iPhone_17_PER_Sept2025.pdf" },
    transparency: "ufficiale",
    acquaL: 12760,
    acquaNota: "Acqua \"nascosta\" media per produrre uno smartphone: estrazione dei metalli e fabbricazione dei chip.",
    acquaFonte: FONTI.waterSmartphone,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "airpods-pro-3",
    emoji: "🎧",
    tile: "#f5f5f7",
    emojiDark: true,
    nome: "Apple AirPods Pro 3",
    marca: "Apple",
    prezzo: 249,
    stelle: 4.7, recensioni: "112.033",
    co2: 13,
    co2Nota: "Ciclo di vita completo, PER Apple. Le batterie incollate non sono sostituibili: a fine vita (~4-5 anni) diventano rifiuto elettronico quasi non riciclabile.",
    co2Fonte: { label: "Apple — AirPods Pro 3 Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/airpods/Apple_AirPods_Pro_3_PER_Sept2025.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "apple-watch-s10",
    emoji: "⌚",
    tile: "#1c1c1e",
    nome: "Apple Watch Series 10",
    marca: "Apple",
    prezzo: 449,
    stelle: 4.8, recensioni: "67.421",
    co2: 8.4,
    co2Nota: "Dato Apple (già al netto delle riduzioni dichiarate). Apple lo vendeva come \"CO₂ neutrale\" grazie a crediti di compensazione: un tribunale tedesco ha vietato questa pubblicità come ingannevole.",
    co2Fonte: { label: "Apple — Apple Watch Series 10 Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/watch/Apple_Watch_Series_10_PER_Sept2024.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto, { text: "Il marketing \"carbon neutral\" di questo prodotto è stato dichiarato ingannevole da un tribunale di Francoforte.", fonte: FONTI.watchRuling }],
  },
  {
    id: "macbook-air-m5",
    emoji: "💻",
    tile: "#1c1c1e",
    nome: "Apple MacBook Air 13\" (M5)",
    marca: "Apple",
    prezzo: 1249,
    stelle: 4.8, recensioni: "23.874",
    co2: 119,
    co2Nota: "Configurazione base, ciclo di vita completo, PER Apple (fino a 165 kg per le configurazioni maggiori).",
    co2Fonte: { label: "Apple — MacBook Air (M5) Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/notebooks/MacBook_Air_M5_PER_Mar2026.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: "I chip avanzati richiedono enormi volumi di acqua ultrapura nelle fonderie di Taiwan, area a ricorrente crisi idrica.",
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "ipad-10",
    emoji: "📲",
    tile: "#1c1c1e",
    nome: "Apple iPad (10ª gen, 64 GB)",
    marca: "Apple",
    prezzo: 439,
    stelle: 4.8, recensioni: "94.115",
    co2: 72,
    co2Nota: "Ciclo di vita completo, PER Apple.",
    co2Fonte: { label: "Apple — iPad (10th generation) Product Environmental Report", url: "https://www.apple.com/environment/pdf/products/ipad/iPad_PER_Oct2022.pdf" },
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "macbook-pro-14-m4",
    emoji: "💻",
    tile: "#1c1c1e",
    nome: "Apple MacBook Pro 14\" (M4)",
    marca: "Apple",
    prezzo: 1849,
    stelle: 4.9, recensioni: "18.204",
    co2: 243,
    co2Nota: "Configurazione base, ciclo di vita completo, Product Environmental Report Apple (ISO 14040/44/67, ottobre 2024). La grande maggioranza nasce in produzione, prima ancora di premere il tasto d'accensione.",
    co2Fonte: FONTI.appleMbpM4,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: "I chip avanzati richiedono enormi volumi di acqua ultrapura nelle fonderie di Taiwan, area a ricorrente crisi idrica.",
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "mac-mini-m4",
    emoji: "🖲️",
    tile: "#1c1c1e",
    nome: "Apple Mac mini (M4)",
    marca: "Apple",
    prezzo: 719,
    stelle: 4.8, recensioni: "12.930",
    co2: 32,
    co2Nota: "Configurazione base, ciclo di vita completo, PER Apple: 32 kg CO₂e. Apple lo comunica come \"carbon neutral\" grazie a crediti di compensazione — ma i 32 kg sono le emissioni reali, prima delle compensazioni.",
    co2Fonte: FONTI.appleMacMiniM4,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto, { text: "Dietro il claim \"carbon neutral\": le emissioni non azzerate vengono coperte da crediti di compensazione, un meccanismo che un tribunale tedesco ha già giudicato pubblicità ingannevole per un altro prodotto Apple.", fonte: FONTI.watchRuling }],
  },
  {
    id: "apple-tv-4k",
    emoji: "📡",
    tile: "#1c1c1e",
    nome: "Apple TV 4K (3ª gen)",
    marca: "Apple",
    prezzo: 169,
    stelle: 4.8, recensioni: "34.771",
    co2: 59,
    co2Nota: "Ciclo di vita completo, PER Apple (ottobre 2022): 59 kg CO₂e, di cui ~50% dalla produzione e ~40% dall'uso. Ridotto di oltre il 25% rispetto alla generazione precedente.",
    co2Fonte: FONTI.appleTvPer,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.foxconn, LAVORO.cobalto],
  },
  {
    id: "ps5",
    emoji: "🎮",
    tile: "#00439c",
    nome: "Sony PlayStation 5",
    marca: "Sony",
    prezzo: 549,
    stelle: 4.8, recensioni: "78.930",
    co2: 89,
    co2Nota: "Sony non pubblica l'LCA completa della PS5: 89 kg è il dato di produzione+trasporto della PS4 (Univ. di Cambridge), usato come proxy prudente. L'uso aggiunge ~0,022 kg CO₂ l'ora: con 2 ore al giorno per 5 anni sono altri ~80 kg.",
    co2Fonte: FONTI.cambridgePs4,
    transparency: "stima",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "switch-2",
    emoji: "🕹️",
    tile: "#e60012",
    nome: "Nintendo Switch 2",
    marca: "Nintendo",
    prezzo: 469,
    stelle: 4.8, recensioni: "51.204",
    co2: null,
    co2Nota: "Nintendo non pubblica alcuna analisi del ciclo di vita. Gli studi indipendenti stimano per la Switch originale ~13,8 kg CO₂ l'anno di solo uso. Il dato di produzione resta un segreto aziendale.",
    co2Fonte: FONTI.mongabayConsole,
    transparency: "assente",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.trasparenzaNintendo, LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "samsung-qled-55",
    emoji: "🖥️",
    tile: "#111111",
    nome: "Samsung QLED 55\" 4K",
    marca: "Samsung",
    prezzo: 649,
    stelle: 4.6, recensioni: "37.617",
    co2: 1123,
    co2Nota: "EPD ufficiale Samsung (QLED 55\", vita 5 anni): 1.122,7 kg CO₂e totali, di cui ~725 kg dal solo uso e ~375 kg da materiali e produzione. L'articolo più pesante di questo negozio.",
    co2Fonte: FONTI.samsungEpd,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.samsungFab, LAVORO.assemblaggiaCina],
  },
  {
    id: "fairphone-5",
    emoji: "📱",
    tile: "#1f6f3c",
    nome: "Fairphone 5 (256 GB)",
    marca: "Fairphone",
    prezzo: 699,
    stelle: 4.5, recensioni: "6.310",
    co2: 42.1,
    co2Nota: "42,1 kg CO₂e sul ciclo di vita, LCA ufficiale Fairphone 2024 (metodo rivisto con Fraunhofer IZM). L'unico del negozio pensato per durare: 10/10 su iFixit, 10 moduli sostituibili, 8-10 anni di aggiornamenti. Tenerlo 5 anni invece di 3 taglia l'impronta annua di circa il 31%.",
    co2Fonte: FONTI.fairphoneLca,
    transparency: "ufficiale",
    acquaL: 12760,
    acquaNota: "Acqua \"nascosta\" media per produrre uno smartphone; qui l'uso prolungato la distribuisce su molti più anni.",
    acquaFonte: FONTI.waterSmartphone,
    lavoro: [LAVORO.fairphoneEtico],
  },
  {
    id: "pixel-9",
    emoji: "📱",
    tile: "#1a73e8",
    nome: "Google Pixel 9 (128 GB)",
    marca: "Google",
    prezzo: 899,
    stelle: 4.6, recensioni: "31.548",
    co2: 64,
    co2Nota: "Ciclo di vita completo, Product Environmental Report ufficiale di Google: 64 kg CO₂e. Come per ogni smartphone, la fetta maggiore è nella produzione dei componenti.",
    co2Fonte: FONTI.googlePixelPer,
    transparency: "ufficiale",
    acquaL: 12760,
    acquaNota: "Acqua \"nascosta\" media per produrre uno smartphone: estrazione dei metalli e fabbricazione dei chip.",
    acquaFonte: FONTI.waterSmartphone,
    lavoro: [LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "galaxy-s24-ultra",
    emoji: "📱",
    tile: "#111111",
    nome: "Samsung Galaxy S24 Ultra (256 GB)",
    marca: "Samsung",
    prezzo: 1299,
    stelle: 4.7, recensioni: "52.117",
    co2: 66.4,
    co2Nota: "Ciclo di vita completo (produzione, distribuzione, 3 anni d'uso, smaltimento) misurato e verificato da Carbon Trust secondo lo standard PAS 2050: 66,4 kg CO₂e. Usa cobalto e terre rare riciclate in alcuni componenti.",
    co2Fonte: FONTI.samsungS24Per,
    transparency: "ufficiale",
    acquaL: 12760,
    acquaNota: "Acqua \"nascosta\" media per produrre uno smartphone: estrazione dei metalli e fabbricazione dei chip.",
    acquaFonte: FONTI.waterSmartphone,
    lavoro: [LAVORO.samsungFab, LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "surface-laptop-13",
    emoji: "💻",
    tile: "#0067b8",
    nome: "Microsoft Surface Laptop 13\"",
    marca: "Microsoft",
    prezzo: 1099,
    stelle: 4.5, recensioni: "9.884",
    co2: 137,
    co2Nota: "Ciclo di vita completo su 4,5 anni d'uso, Eco Profile ufficiale Microsoft: 137 kg CO₂e (produzione 102, trasporto 18, uso 17, fine vita <1).",
    co2Fonte: FONTI.microsoftSurface,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "dell-xps-13",
    emoji: "💻",
    tile: "#3a3a3a",
    nome: "Dell XPS 13 (9350)",
    marca: "Dell",
    prezzo: 1399,
    stelle: 4.5, recensioni: "14.226",
    co2: 265,
    co2Nota: "265 kg CO₂e sul ciclo di vita, datasheet PCF ufficiale Dell (2024). È una stima statistica dichiarata dal produttore (metodo PAIA, ISO 14040) con incertezza ±48 kg: ~81% dell'impatto è nella produzione.",
    co2Fonte: FONTI.dellXps,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: "La fabbricazione dei chip richiede grandi volumi di acqua ultrapura.",
    lavoro: [LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "mx-master-3s",
    emoji: "🖱️",
    tile: "#2b2b2b",
    nome: "Logitech MX Master 3S",
    marca: "Logitech",
    prezzo: 119.99,
    stelle: 4.8, recensioni: "76.540",
    co2: 7.78,
    co2Nota: "7,78 kg CO₂e sul ciclo di vita (manifattura, trasporto, uso su 2 anni, fine vita), Product Carbon Footprint dichiarato da Logitech con revisione critica ISO 14067 di DEKRA. Il più leggero del negozio — ma è pur sempre un mouse.",
    co2Fonte: FONTI.logitechPcf,
    transparency: "ufficiale",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.logitechEtichetta, LAVORO.assemblaggiaCina, LAVORO.cobaltoGenerico],
  },
  {
    id: "lego-1000",
    emoji: "🧱",
    tile: "#ffcf00",
    emojiDark: true,
    nome: "Set LEGO da ~1.000 pezzi",
    marca: "LEGO",
    prezzo: 159.99,
    stelle: 4.9, recensioni: "28.442",
    co2: 40,
    co2Nota: "Stima 20-60 kg CO₂e per 1.000 mattoncini in ABS (qui usiamo il valore centrale, 40 kg). Servono ~2 kg di petrolio per ogni kg di ABS; il piano LEGO per mattoncini in PET riciclato è stato abbandonato perché avrebbe aumentato le emissioni.",
    co2Fonte: FONTI.legoFortune,
    transparency: "stima",
    acquaL: null,
    acquaNota: null,
    lavoro: [LAVORO.legoOk],
  },
];

// Foto dei prodotti: og:image ufficiali dei produttori (hotlink) oppure
// Wikimedia Commons (licenze libere); fotoPage = pagina di provenienza/attribuzione.
const FOTO = {
  "fire-tv-stick-4k": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Amazon_Fire_TV_4k.jpg/960px-Amazon_Fire_TV_4k.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Amazon_Fire_TV_4k.jpg" },
  "kindle-paperwhite": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/2023_Amazon_Kindle_Paperwhite_%281%29.jpg/960px-2023_Amazon_Kindle_Paperwhite_%281%29.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:2023_Amazon_Kindle_Paperwhite_(1).jpg" },
  "ring-battery-doorbell": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Ring_Video_Doorbell_2.jpg/960px-Ring_Video_Doorbell_2.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Ring_Video_Doorbell_2.jpg" },
  "blink-mini-2": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Blink_Mini_Security_Camera.jpg/960px-Blink_Mini_Security_Camera.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Blink_Mini_Security_Camera.jpg" },
  "iphone-17": { foto: "https://www.apple.com/v/iphone-17/g/images/meta/iphone-17_overview__cg0rlzmbhl7m_og.png", fotoPage: "https://www.apple.com/iphone-17/" },
  "airpods-pro-3": { foto: "https://www.apple.com/v/airpods-pro/s/images/meta/og__c0ceegchesom_overview.png", fotoPage: "https://www.apple.com/airpods-pro/" },
  "apple-watch-s10": { foto: "https://www.apple.com/assets-www/en_WW/watch/og/watch_og_1ff2ee953.png", fotoPage: "https://www.apple.com/apple-watch-series-10/" },
  "macbook-air-m5": { foto: "https://www.apple.com/v/macbook-air/z/images/meta/macbook_air_mx__ez5y0k5yy7au_og.png", fotoPage: "https://www.apple.com/macbook-air/" },
  "ipad-10": { foto: "https://www.apple.com/v/ipad-11/d/images/meta/ipad-11_overview__brh97xhhd8b6_og.png", fotoPage: "https://www.apple.com/ipad-11/" },
  "ps5": { foto: "https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21", fotoPage: "https://www.playstation.com/en-us/ps5/" },
  "switch-2": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Nintendo_Switch_2_in_Docking_Console.jpg/960px-Nintendo_Switch_2_in_Docking_Console.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Nintendo_Switch_2_in_Docking_Console.jpg" },
  "samsung-qled-55": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Samsung_QLED_TV_8K_-_75_inches_-_2018-11-02.jpg/960px-Samsung_QLED_TV_8K_-_75_inches_-_2018-11-02.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Samsung_QLED_TV_8K_-_75_inches_-_2018-11-02.jpg" },
  "fairphone-5": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Fairphone_5.png/960px-Fairphone_5.png", fotoPage: "https://commons.wikimedia.org/wiki/File:Fairphone_5.png" },
  "pixel-9": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Google_Pixel_9_%28Porcelain%29_front.svg/960px-Google_Pixel_9_%28Porcelain%29_front.svg.png", fotoPage: "https://commons.wikimedia.org/wiki/File:Google_Pixel_9_(Porcelain)_front.svg" },
  "galaxy-s24-ultra": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Samsung_S24_Ultra_Phone.png/960px-Samsung_S24_Ultra_Phone.png", fotoPage: "https://commons.wikimedia.org/wiki/File:Samsung_S24_Ultra_Phone.png" },
  "mac-mini-m4": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/MacMiniM4.jpg/960px-MacMiniM4.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:MacMiniM4.jpg" },
  "dell-xps-13": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Dell_XPS_13_9350.jpg/960px-Dell_XPS_13_9350.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Dell_XPS_13_9350.jpg" },
  "lego-1000": { foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Lego_Space_-_Set_462_Mobile_Rocket_Launcher_%287465210278%29.jpg/960px-Lego_Space_-_Set_462_Mobile_Rocket_Launcher_%287465210278%29.jpg", fotoPage: "https://commons.wikimedia.org/wiki/File:Lego_Space_-_Set_462_Mobile_Rocket_Launcher_(7465210278).jpg" },
};
PRODOTTI.forEach((p) => Object.assign(p, FOTO[p.id]));

// Fattori per le equivalenze dello scontrino (valori medi, indicativi)
const EQUIV = {
  kgCo2PerKmAuto: 0.17,   // auto media europea, uso reale
  kgCo2PerAlberoAnno: 25, // assorbimento medio annuo di un albero
  litriPerDoccia: 65,     // doccia media
};
